### ISSUE TITLE
x86_64-linux-gnu-gcc: error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such file or directory

### ISSUE THREAD

**Issue by wenyang1112** [HKUST-Aerial-Robotics/Stereo-RCNN#11]
hello, how to solve this problem "x86_64-linux-gnu-gcc: error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such file or directory"

**Comment by PeiliangLi** [comment]
Hi, have you run the sh make.sh successfully?

**Comment by wenyang1112** [comment]
no，when I run sh make.sh, it occurs this error


 
---Original---

**Comment by PeiliangLi** [comment]
Please put your complete error log here.

**Comment by wenyang1112** [comment]
the complete error :
 root@8a96780ffcc1:/home/wy/Stereo-RCNN-master/lib# sh make.sh
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
make.sh: 25: make.sh: nvcc: not found
/home/wy/Stereo-RCNN-master/lib/model/nms
['/home/wy/Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpryc2Jy/_nms.c
setting the current directory to '/tmp/tmpryc2Jy'
running build_ext
building '_nms' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/include/python2.7 -c _nms.c -o ./_nms.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -std=c99 ./_nms.o /home/wy/Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o -o ./_nms.so
x86_64-linux-gnu-gcc: error: /home/wy/Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "build.py", line 37, in <module>
    ffi.build()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cffi/recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "/usr/local/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/local/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1
Compiling roi align kernels by nvcc...
make.sh: 35: make.sh: nvcc: not found
/home/wy/Stereo-RCNN-master/lib/model/roi_align
generating /tmp/tmpZ_dL0v/_roi_align.c
setting the current directory to '/tmp/tmpZ_dL0v'
running build_ext
building '_roi_align' extension
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -std=c99 -fPIC -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include -I/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/../../lib/include/TH -I/usr/include/python2.7 -c _roi_align.c -o ./_roi_align.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -std=c99 ./_roi_align.o /home/wy/Stereo-RCNN-master/lib/model/roi_align/src/roi_align_kernel.cu.o -o ./_roi_align.so
x86_64-linux-gnu-gcc: error: /home/wy/Stereo-RCNN-master/lib/model/roi_align/src/roi_align_kernel.cu.o: No such file or directory
Traceback (most recent call last):
  File "build.py", line 35, in <module>
    ffi.build()
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 167, in build
    _build_extension(ffi, cffi_wrapper_name, target_dir, verbose)
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/ffi/__init__.py", line 103, in _build_extension
    ffi.compile(tmpdir=tmpdir, verbose=verbose, target=libname)
  File "/usr/local/lib/python2.7/dist-packages/cffi/api.py", line 723, in compile
    compiler_verbose=verbose, debug=debug, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/cffi/recompiler.py", line 1526, in recompile
    compiler_verbose, debug)
  File "/usr/local/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 22, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose, debug)
  File "/usr/local/lib/python2.7/dist-packages/cffi/ffiplatform.py", line 58, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.VerificationError: LinkError: command 'x86_64-linux-gnu-gcc' failed with exit status 1

  

 

 ------------------ 原始邮件 ------------------
  发件人: "Peiliang"<notifications@github.com>;
 发送时间: 2019年5月7日(星期二) 中午1:25
 收件人: "HKUST-Aerial-Robotics/Stereo-RCNN"<Stereo-RCNN@noreply.github.com>;
 抄送: "wy"<2453079161@qq.com>; "Author"<author@noreply.github.com>; 
 主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] x86_64-linux-gnu-gcc:error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such fileor directory (#11)

 

 
Please put your complete error log here.

**Comment by PeiliangLi** [comment]
hi, @wenyang1112 , what's your gcc version?

**Comment by wenyang1112** [comment]
my gcc version:  gcc (Ubuntu 5.4.0-6ubuntu1~16.04.11) 5.4.0 20160609





------------------ 原始邮件 ------------------
发件人: "Peiliang"<notifications@github.com>;
发送时间: 2019年5月9日(星期四) 上午8:38
收件人: "HKUST-Aerial-Robotics/Stereo-RCNN"<Stereo-RCNN@noreply.github.com>;
抄送: "wy"<2453079161@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] x86_64-linux-gnu-gcc:error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such fileor directory (#11)




hi, @wenyang1112 , what's your gcc version?

**Comment by PeiliangLi** [comment]
Could you please try gcc-4.8?
`sudo apt-get install --reinstall gcc-4.8`

**Comment by PeiliangLi** [comment]
The gcc version is same with mine. What's your `nvcc --version` output?

**Comment by wenyang1112** [comment]
the output :
 nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2016 NVIDIA Corporation
Built on Tue_Jan_10_13:22:03_CST_2017
Cuda compilation tools, release 8.0, V8.0.61


 

 ------------------ 原始邮件 ------------------
  发件人: "Peiliang"<notifications@github.com>;
 发送时间: 2019年5月9日(星期四) 中午12:28
 收件人: "HKUST-Aerial-Robotics/Stereo-RCNN"<Stereo-RCNN@noreply.github.com>;
 抄送: "wy"<2453079161@qq.com>; "Mention"<mention@noreply.github.com>; 
 主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] x86_64-linux-gnu-gcc:error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such fileor directory (#11)

 

 
The gcc version is same with mine. What's your nvcc --version output?

**Comment by wenyang1112** [comment]
I have changed my gcc version, but it doesn't work
  

 

 ------------------ 原始邮件 ------------------
  发件人: "Peiliang"<notifications@github.com>;
 发送时间: 2019年5月9日(星期四) 中午12:28
 收件人: "HKUST-Aerial-Robotics/Stereo-RCNN"<Stereo-RCNN@noreply.github.com>;
 抄送: "wy"<2453079161@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] x86_64-linux-gnu-gcc:error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such fileor directory (#11)

 

 
The gcc version is same with mine. What's your nvcc --version output?

**Comment by PeiliangLi** [comment]
It's weird. Your pytorch version is also 0.3.0.post4, right?

**Comment by wenyang1112** [comment]
yes,
 >>> print(torch.__version__)
0.3.0.post4

  

 

 ------------------ 原始邮件 ------------------
  发件人: "Peiliang"<notifications@github.com>;
 发送时间: 2019年5月11日(星期六) 凌晨3:01
 收件人: "HKUST-Aerial-Robotics/Stereo-RCNN"<Stereo-RCNN@noreply.github.com>;
 抄送: "wy"<2453079161@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] x86_64-linux-gnu-gcc:error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such fileor directory (#11)

 

 
It's weird. Your pytorch version is also 0.3.0.post4, right?

**Comment by PeiliangLi** [comment]
I found a similar issue: https://github.com/jwyang/faster-rcnn.pytorch/issues/112.
Could you please try the advice mentioned in this issue?

**Comment by wenyang1112** [comment]
thanks, I solve the problem, but when I run python demo.py, it occurs another error:
 Traceback (most recent call last):
  File "demo.py", line 26, in <module>
    from roi_data_layer.roidb import combined_roidb
  File "/home/wy/Stereo-RCNN-master/lib/roi_data_layer/roidb.py", line 9, in <module>
    from datasets.factory import get_imdb
  File "/home/wy/Stereo-RCNN-master/lib/datasets/factory.py", line 14, in <module>
    from datasets.kitti import kitti
  File "/home/wy/Stereo-RCNN-master/lib/datasets/kitti.py", line 27, in <module>
    from .imdb import imdb
  File "/home/wy/Stereo-RCNN-master/lib/datasets/imdb.py", line 15, in <module>
    from lib.model.utils.cython_bbox import bbox_overlaps
ImportError: No module named lib.model.utils.cython_bbox

  

 

 ------------------ 原始邮件 ------------------
  发件人: "Peiliang"<notifications@github.com>;
 发送时间: 2019年5月11日(星期六) 中午11:32
 收件人: "HKUST-Aerial-Robotics/Stereo-RCNN"<Stereo-RCNN@noreply.github.com>;
 抄送: "wy"<2453079161@qq.com>;"Mention"<mention@noreply.github.com>;
 主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] x86_64-linux-gnu-gcc:error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such fileor directory (#11)

 

 
I found a similar issue: jwyang/faster-rcnn.pytorch#112.
Could you please try the advice mentioned in this issue?

**Comment by PeiliangLi** [comment]
Just remove this line: from lib.model.utils.cython_bbox import bbox_overlaps,
I fixed this issue in the latest commit.

**Comment by Propantheline** [comment]
> thanks, I solve the problem, but when I run python demo.py, it occurs another error: Traceback (most recent call last): File "demo.py", line 26, in <module> from roi_data_layer.roidb import combined_roidb File "/home/wy/Stereo-RCNN-master/lib/roi_data_layer/roidb.py", line 9, in <module> from datasets.factory import get_imdb File "/home/wy/Stereo-RCNN-master/lib/datasets/factory.py", line 14, in <module> from datasets.kitti import kitti File "/home/wy/Stereo-RCNN-master/lib/datasets/kitti.py", line 27, in <module> from .imdb import imdb File "/home/wy/Stereo-RCNN-master/lib/datasets/imdb.py", line 15, in <module> from lib.model.utils.cython_bbox import bbox_overlaps ImportError: No module named lib.model.utils.cython_bbox
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "Peiliang"<notifications@github.com>; 发送时间: 2019年5月11日(星期六) 中午11:32 收件人: "HKUST-Aerial-Robotics/Stereo-RCNN"<Stereo-RCNN@noreply.github.com>; 抄送: "wy"<2453079161@qq.com>;"Mention"<mention@noreply.github.com>; 主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] x86_64-linux-gnu-gcc:error:Stereo-RCNN-master/lib/model/nms/src/nms_cuda_kernel.cu.o: No such fileor directory (#11) I found a similar issue: [jwyang/faster-rcnn.pytorch#112](https://github.com/jwyang/faster-rcnn.pytorch/issues/112). Could you please try the advice mentioned in this issue? — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Hi,can you tell me how you solved this problem?
