### ISSUE TITLE
'module' object has no attribute 'nms_cuda'

### ISSUE THREAD

**Issue by Stephen-ThreeD** [HKUST-Aerial-Robotics/Stereo-RCNN#12]
Hi, I have run the sh make.sh, and the result is down here, it seems no problem.
**************************************************************************************
running build_ext
skipping 'model/utils/bbox.c' Cython extension (up-to-date)
Compiling nms kernels by nvcc...
/unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/nms
['/unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/nms/src/nms_cuda_kernel.cu.o']
generating /tmp/tmpFagalR/_nms.c
setting the current directory to '/tmp/tmpFagalR'
running build_ext
building '_nms' extension
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/lihuidong/anaconda3/envs/env_stereo/lib/python2.7/s
ite-packages/torch/utils/ffi/../../lib/include -I/home/lihuidong/anaconda3/envs/env_stereo/lib/python2.7/site-packages/torch/utils/ffi/..
/../lib/include/TH -I/home/lihuidong/anaconda3/envs/env_stereo/include/python2.7 -c _nms.c -o ./_nms.o
gcc -pthread -shared -L/home/lihuidong/anaconda3/envs/env_stereo/lib -Wl,-rpath=/home/lihuidong/anaconda3/envs/env_stereo/lib,--no-as-nee
ded -std=c99 ./_nms.o /unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/nms/src/nms_cuda_kernel.cu.o -L/home/lihui
dong/anaconda3/envs/env_stereo/lib -lpython2.7 -o ./_nms.so
Compiling roi align kernels by nvcc...
/unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/roi_align
generating /tmp/tmp8G3ipN/_roi_align.c
setting the current directory to '/tmp/tmp8G3ipN'
running build_ext
building '_roi_align' extension
gcc -pthread -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -std=c99 -fPIC -I/home/lihuidong/anaconda3/envs/env_stereo/lib/python2.7/s
ite-packages/torch/utils/ffi/../../lib/include -I/home/lihuidong/anaconda3/envs/env_stereo/lib/python2.7/site-packages/torch/utils/ffi/..
/../lib/include/TH -I/home/lihuidong/anaconda3/envs/env_stereo/include/python2.7 -c _roi_align.c -o ./_roi_align.o
gcc -pthread -shared -L/home/lihuidong/anaconda3/envs/env_stereo/lib -Wl,-rpath=/home/lihuidong/anaconda3/envs/env_stereo/lib,--no-as-nee
ded -std=c99 ./_roi_align.o /unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/roi_align/src/roi_align_kernel.cu.o 
-L/home/lihuidong/anaconda3/envs/env_stereo/lib -lpython2.7 -o ./_roi_align.so
**************************************************************************************

But when I run bash train.sh, I got this issue and don't know how to solve it, can you help me to figure it out?

**************************************************************************************
Traceback (most recent call last):
  File "trainval_net.py", line 212, in <module>
    gt_boxes_merge, gt_dim_orien, gt_kpts, num_boxes)
  File "/home/lihuidong/anaconda3/envs/env_stereo/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/stereo_rcnn/stereo_rcnn.py", line 195, in forward
    im_info, gt_boxes_left, gt_boxes_right, gt_boxes_merge, num_boxes)
  File "/home/lihuidong/anaconda3/envs/env_stereo/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/rpn/stereo_rpn.py", line 101, in forward
    im_info, cfg_key, rpn_shapes))
  File "/home/lihuidong/anaconda3/envs/env_stereo/lib/python2.7/site-packages/torch/nn/modules/module.py", line 325, in __call__
    result = self.forward(*input, **kwargs)
  File "/unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/rpn/proposal_layer.py", line 122, in forward
    keep_idx_i_left = nms(torch.cat((proposals_single_left, scores_single), 1), nms_thresh, force_cpu=not cfg.USE_GPU_NMS)
  File "/unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/nms/nms_wrapper.py", line 21, in nms
    return nms_gpu(dets, thresh) if force_cpu == False else nms_cpu(dets, thresh)
  File "/unsullied/sharefs/lihuidong/isilon_home/workspace/stereo-RCNN/lib/model/nms/nms_gpu.py", line 10, in nms_gpu
    nms.nms_cuda(keep, dets, num_out, thresh)
AttributeError: 'module' object has no attribute 'nms_cuda'

**Comment by PeiliangLi** [comment]
I put some useful link from the original faster-rcnn.pytorch repo.
https://github.com/jwyang/faster-rcnn.pytorch/issues?utf8=%E2%9C%93&q=nms_cuda
Hope it is helpful.
