### ISSUE TITLE
how can I work this project on pytorch 1.0

### ISSUE THREAD

**Issue by stoneeve415** [HKUST-Aerial-Robotics/Stereo-RCNN#14]
can you give a branch of pytorch-1.0

**Comment by PeiliangLi** [comment]
Yes, I will do it some weekend.

**Comment by PeiliangLi** [comment]
Pytorch 1.0 is supported now. Please checkout to https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/tree/1.0 for the details.

**Comment by stoneeve415** [comment]
Hi，@PeiliangLi ，Thank you so much for your great work! 
I wonder if there is some files missing in folder Stereo-RCNN/lib/model. when I run `sh make.sh`, the terminal print error like ' roi_pooling_kernel.cu: No such file or directory', so I checked the make.sh, there is no such file when compile roi_pooling and roi_crop.

**Comment by PeiliangLi** [comment]
Are you using the 1.0 branch? Please follow the readme carefully. The instructions are different from the master branch.

**Comment by stoneeve415** [comment]
Thank you very much, it work properly now. the 1.0 branch should run `python setup.py build develop` instead of 'sh make.sh'.
