### ISSUE TITLE
Does the code support multi GPUs for training?

### ISSUE THREAD

**Issue by cxzhou95** [HKUST-Aerial-Robotics/Stereo-RCNN#15]
Hi, 
I modify CUDA_VISIBLE_DEVICES=0,1,2,3 in train.sh, but only GPU 0 works.
Does this code support multi GPUs?

And each iter takes about 1.97s with a single Titan Xp (cuda8.0) when training.  It will take about 75 hours for 20epoch. Is it normal?

**Comment by PeiliangLi** [comment]
Currently, it does not support multi GPUs, but feel free to contribute it if you are interested. 
1.97s is not normal. On my machine, it takes about 1s per-frame for training using TITAN Xp.
