### ISSUE TITLE
Support CUDA > 9.0...

### ISSUE THREAD

**Issue by thully** [HKUST-Aerial-Robotics/Stereo-RCNN#16]
With CUDA 9.2 installed, I am unable to build the stereo-rcnn project.  Following the instructions on the wiki installs a version of PyTorch that is built for CUDA 8.0 (and complains about missing CUDA 8.0 libraries when building). Changing the cuda80 argument to cuda92 makes no difference, as there seems to be no CUDA 9.2 version of PyTorch 0.3.0 (there is for later versions, but the wiki suggests these aren't supported).

The only thing that ultimately worked was downgrading to CUDA 9.0 and using the cuda90 argument when installing PyTorch. While I could run make.sh by using the cuda90 PyTorch with CUDA 9.2, I couldn't actually run the demo without downgrading CUDA itself. 

It seems this package needs to be updated to support newer versions of PyTorch and/or CUDA. As it stands, CUDA 9.0 is not officially supported on Ubuntu 18.04 (the current LTS), or by PyTorch 0.3.0.  In the meantime, it would help to document the incompatibility with recent CUDA versions...

**Comment by PeiliangLi** [comment]
OK, I will update to pytorch 1.0 soon.

**Comment by congyingTech** [comment]
hello, cuda90 is still not support...

**Comment by PeiliangLi** [comment]
🚩 This weekend!

**Comment by PeiliangLi** [comment]
Pytorch 1.0 is supported now. Please checkout to https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/tree/1.0 for the details.
Feel free to post any issue here.
