### ISSUE TITLE
type error in mono 

### ISSUE THREAD

**Issue by shammmmmless** [HKUST-Aerial-Robotics/Stereo-RCNN#17]
when I run demo in mono version, the error is shown as following:

Traceback (most recent call last):
  File "demo.py", line 261, in <module>
    calib, alpha, dim, box_left, cls_kpts[detect_idx])
  File "/home/user/Cworkspace/Stereo-RCNN-mono/lib/model/utils/box_estimator.py", line 212, in solve_x_y_z_theta_from_kpt
    alpha = kpt2alpha(kpt_pos, kpt_type, box_left)
  File "/home/user/Cworkspace/Stereo-RCNN-mono/lib/model/utils/box_estimator.py", line 159, in kpt2alpha
    alpha = -m.pi/2 - m.asin(clamp((kpt_pos-box[0])/box_width,-1,1))   # 0 -> -90, 1 -> -180
TypeError: sub() received an invalid combination of arguments - got (numpy.float32), but expected one of:
 * (Tensor other, float alpha)
 * (float other, float alpha)

It was running with python=2.7.6 and pytorch=0.3.0.

**Comment by PeiliangLi** [comment]
I haven't meet this issue before, could you try to change the line
`calib, alpha, dim, box_left, cls_kpts[detect_idx])`
to
`calib, alpha, dim, box_left, cls_kpts[detect_idx].cpu().numpy())`

**Comment by shammmmmless** [comment]
It work, but I got a new type error about dense_align now,

Traceback (most recent call last):
  File "demo.py", line 277, in <module>
    boxes_all[:,0:4], kpts_all, poses_all[:,0:7])
  File "/home/user/Cworkspace/Stereo-RCNN-mono/lib/model/dense_align/dense_align.py", line 264, in align_parallel
    dis_init = f*bl/poses[:,2]
RuntimeError: Expected object of type torch.DoubleTensor but found type torch.cuda.FloatTensor for argument #2 'other'

**Comment by shammmmmless** [comment]
what the version of torchvision should I use?

**Comment by PeiliangLi** [comment]
Change f and bl to float Tensor.
According to my experience, this error only happens when using pytorch1.0 but not for pytorch0.3.0.post4.
Can you print your `torch.__version__`?

**Comment by shammmmmless** [comment]
Thanks a lot! The problem is the version of pytorch, the demo was running in the env of conda, but got the pytorch of system, it fixed.
