### ISSUE TITLE
nvcc/cuda version prolems

### ISSUE THREAD

**Issue by undefinedzero** [HKUST-Aerial-Robotics/Stereo-RCNN#2]
- Ubuntu 18.04
- CUDA 10.0

At first, I used nvcc(version 10.0) and changed the CUDA_PATH in `lib/make.sh` to the cuda lib in anaconda(version 8.0) to run `lib/make.sh`, but I met `undefined symbol: __cudaPopCallConfiguration` problem. It seemed that I need to use nvcc 8.0 to compile the code.
Then, I installed CUDA 8.0 and use its nvcc 8.0 to compile the code again and it works.
So, I think in order to run the code, we need CUDA 8.0 toolkit not only in anaconda.

**Comment by PeiliangLi** [comment]
Hi, thanks for pointing this.
We haven't test CUDA 10.0 yet, but 8.0 and 9.0 should both be ok.
