### ISSUE TITLE
Camera parameters

### ISSUE THREAD

**Issue by lizhiqiang-1996** [HKUST-Aerial-Robotics/Stereo-RCNN#30]
Hello, I want to apply this network to another binocular cameras. Is there any camera parameter file that I need to modify? Thank you.

**Comment by PeiliangLi** [comment]
Hi, the dataset loader is in this file: https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/blob/master/lib/datasets/kitti.py, and we read the image data and calibration file in this file: https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/blob/master/lib/model/utils/kitti_utils.py#L97
