### ISSUE TITLE
about dataset

### ISSUE THREAD

**Issue by qazzombie** [HKUST-Aerial-Robotics/Stereo-RCNN#32]
The velodyne in the requested dataset is data_odometry_velodyne or data_object_velodyne

**Comment by PeiliangLi** [comment]
Stereo R-CNN doesn't need Velodyne data.

**Comment by qazzombie** [comment]
> Stereo R-CNN doesn't need Velodyne data.

But showing the need in the readme,Can you tell me how to put this data set,Need to include a testing set?

**Comment by PeiliangLi** [comment]
For evaluating on the validation dataset, you don't neet to download the test set.
