### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by MQZhang2014** [HKUST-Aerial-Robotics/Stereo-RCNN#36]
Sorry to disturb. I met the error when I ran the command: $ python demo.py
And the error shows like this:
Traceback (most recent call last):
  File "demo.py", line 29, in <module>
    from model.roi_layers import nms
  File "/Stereo-RCNN/lib/model/roi_layers/__init__.py", line 3, in <module>
    from .nms import nms
  File "/Stereo-RCNN/lib/model/roi_layers/nms.py", line 3, in <module>
    from model import _C
ImportError: /Stereo-RCNN/lib/model/_C.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail37_typeMetaDataInstance_preallocated_30E

I ran this on Ubuntu 16.04, Python  3.6.8, CUDA 9.0, pytorch 1.1.0.
I have search a lot to try to solve this issue, but it didn't work.

**Comment by MQZhang2014** [comment]
Someone said that it is because the mismatch version of Pytorch.  I have tried both version 1.0.0 and 1.1.0, however it doesn't work. Thank you.

**Comment by MQZhang2014** [comment]
I finally find that it is because of the torchvision. I uninstall the original torchvision by command 
$conda uninstall torchvision
and then reinstall it.

**Comment by cts666** [comment]
wa oh u are so smart

**Comment by cts666** [comment]
wa oh u are so beautiful

**Comment by cts666** [comment]
wa oh u are zmq
