### ISSUE TITLE
about training

### ISSUE THREAD

**Issue by qazzombie** [HKUST-Aerial-Robotics/Stereo-RCNN#37]
there have  training and testing folders after released the compressed package of image_2.could you tell me the structure of dataset,I want to train this model

**Comment by PeiliangLi** [comment]
We list the structure in the readme, and you can also download the KITTI object dataset for reference.

**Comment by qazzombie** [comment]
> We list the structure in the readme, and you can also download the KITTI object dataset for reference.

Does that contain test data sets?

**Comment by PeiliangLi** [comment]
You can download the test set from the kitti website
