### ISSUE TITLE
About the Vt constraint in box estimator

### ISSUE THREAD

**Issue by chenchr** [HKUST-Aerial-Robotics/Stereo-RCNN#38]
Hello. Thanks for the code.
I have a question about the Vt (top edge of left 2D box) constraint.
It seems that this implementation hardcodes the vertex that should project to the top edge of left 2D box.
Maybe it's based on the assumption that the camera is able to see the top plane of 3D box ?
However, when the top plane of 3D box is invisible, this specific vertex seems depends on the observation angle and viewpoint as well.

**Comment by PeiliangLi** [comment]
Basically, the top plane of the 3D box will be visible in driving scenarios. 
In other scenarios (indoor scene, etc), the top plane of the 3D box might be invisible if the camera has 3-DoF rotation, where we need 3-axis viewpoints estimation to determine the 3D-2D relations.
