### ISSUE TITLE
There is no model.utils.cython_bbox 

### ISSUE THREAD

**Issue by sybilWsybil** [HKUST-Aerial-Robotics/Stereo-RCNN#4]
from model.utils.cython_bbox import bbox_overlaps is wrong in
lib.datasets.imdb.py,there is no cython_bbox

**Comment by PeiliangLi** [comment]
Hi, did you install the requirements (include cython) and run make.sh successfully?

**Comment by sybilWsybil** [comment]
yes,now i have another question:i used CUDA9.0 , pytorch 0.3.1 torchvision 0.2.1 ,I have RuntimeError:cuda runtime erro(48):no kernel image is available for execution on the device at /pytorch /torch/lib/THC/THCTensorCopy.cu:204

**Comment by PeiliangLi** [comment]
According to #6 , there might be some issues with pytorch 0.3.1. You can try 0.3.0 instead.

**Comment by sybilWsybil** [comment]
OK，thanks

**Comment by a785448726** [comment]
The previous problem was solved. But now there is a new problem: "ImportError: No module named cython_bbox". I see you've answered this question before, and I make an error when I run make.sh.
