### ISSUE TITLE
How to get the label of image3(right image)

### ISSUE THREAD

**Issue by dropletpeace** [HKUST-Aerial-Robotics/Stereo-RCNN#40]
Dear Li:
Thanks a lot for sharing your code!
But I'm quite confused how do you get the GT label of the right image during RPN stage.
Looking forward to your reply. 
Best wishes.

**Comment by PeiliangLi** [comment]
Because the extrinsic parameter is given, so we can project the 3D bounding box to the right image to get the 2D box.
Please refer to https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/blob/master/lib/model/utils/kitti_utils.py#L223

**Comment by dropletpeace** [comment]
Great appreciation for your reply!
May I ask a personal question?
If I want to project the Lidar point from the velodyne coordinate system to camera 3 coordinate system, what's projection equation like?

**Comment by PeiliangLi** [comment]
https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/blob/master/lib/model/utils/kitti_utils.py#L303

**Comment by dropletpeace** [comment]
> https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/blob/master/lib/model/utils/kitti_utils.py#L303

Thanks for your reply, but it's the transform to camera2, how to get the coordinate under camera3?

**Comment by PeiliangLi** [comment]
You can transform it to any frame following this function.

**Comment by dropletpeace** [comment]
> You can transform it to any frame following this function.

Thanks for your patience.
But I found that while projecting the lidar cloud to camera2, your code is a little different from that in AVOD.
https://github.com/kujason/wavedata/blob/c4b5aabd9eb3b74fad777349f75161032d3460fa/wavedata/tools/core/calib_utils.py#L371
And the result is a little different.
Best wishes.

**Comment by PeiliangLi** [comment]
Seems the kitti 3D object label is on the camera_2 frame, so we calculate the extrinsic between the camera_3 and camera2, then transform it to the camera_3 frame.
You can easily validate it by visualizing the 3D box on the right image.
