### ISSUE TITLE
RuntimeError: Not compiled with GPU support Stereo-RCNN/lib/model/csrc/nms.h:22

### ISSUE THREAD

**Issue by haleqiu** [HKUST-Aerial-Robotics/Stereo-RCNN#43]
When running `python3 demo.py` I met a problem running `nvidia-docker` 
with cuda 9.0 torch 1.01 torchvision 0.4.0

After `python3 setup.py build develop`
`RuntimeError: Not compiled with GPU support (nms at /home/yuhengq/Stereo-RCNN/lib/model/csrc/nms.h:22)`

**Comment by haleqiu** [comment]
I met a problem running nvidia-docker with cuda 9.0 torch 1.01 torchvision 0.4.0

After `python3 setup.py build develop`, I run `python3 demo.py` which return the error
line 121, in forward
    keep_idx_i_left = nms(proposals_single_left, scores_single.squeeze(1), nms_thresh)
RuntimeError: Not compiled with GPU support (nms at /home/yuhengq/Stereo-RCNN/lib/model/csrc/nms.h:22)

**Comment by haleqiu** [comment]
When `python3 setup.py build develop`
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda' running install

**Comment by Hexuanfang** [comment]
hi，i've met the same problem with you, could you please tell me how did you fix it? thanks in advance

**Comment by haleqiu** [comment]
@Hexuanfang It has been a long time. I am sorry I can't remember all details clearly.
I think this is a Cuda configuration or installation issue. Try to verify your cuda version and installation. BTW, I suggest you configure this with conda, which definitely saves your time.

**Comment by Hexuanfang** [comment]
thanks a lot



---Original---
