### ISSUE TITLE
What's the difference between checkpoint 12_6477 and 20_6477?

### ISSUE THREAD

**Issue by ootts** [HKUST-Aerial-Robotics/Stereo-RCNN#44]
I downloaded a checkpoint days ago from your readme called 12_6477,and get 98,89,80 2D AP from this checkpoint, which is not the same as the 2D AP in your paper. But now I notice that there is only a 20_6477 checkpoint, so what's the difference between these two checkpoints?

**Comment by PeiliangLi** [comment]
In the original paper, we train 20 epoch and evaluate the performance use 20_6477. After upgrading to pytorch 1.0, I found the model converge just after 12 epoch, so I upload the 12_6477 as the default checkpoint in pytorch 1.0 branch. I didn't pay much attention on the 2D detection AP.

**Comment by Sukaiqi** [comment]
Hello, I have the same question, get 98,89,80 2D AP from 12_6477checkpoint. It also happened as a result of my training. why is the hard value so high?
