### ISSUE TITLE
What does 'mono branch' mean? Where the light-wights ? My GPU is 8g, how can i train? Thank you very much

### ISSUE THREAD

**Issue by wyr123456** [HKUST-Aerial-Robotics/Stereo-RCNN#49]

**Comment by PeiliangLi** [comment]
As we mentioned in the readme:  We also provide a light-weight version based on the monocular 2D detection, which only uses stereo images in the dense alignment module. This means the network only needs the monocular image, so training it requires less memory.

**Comment by wyr123456** [comment]
Thank you for your patient answer！

**Comment by wyr123456** [comment]
Is your cuda' version 8.0？ Mine is cuda8.0 too and when i ran demo.py there is the problem "RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25"  Could you give me any suggestion please.

**Comment by PeiliangLi** [comment]
If you use master or mono branch, please use 0.3.0 pytorch as we recommend in the readme.
If you use 1.0 branch, please use 1.0.0 pytorch.

**Comment by wyr123456** [comment]
Is your cuda' version 8.0？ Mine is cuda8.0 too and when i ran demo.py there is the problem "RuntimeError: cuda runtime error (30) : unknown error at /pytorch/aten/src/THC/THCTensorRandom.cu:25"  Could you give me any suggestion please.

**Comment by wyr123456** [comment]
> If you use master or mono branch, please use 0.3.0 pytorch as we recommend in the readme.
> If you use 1.0 branch, please use 1.0.0 pytorch.

 It did work, thank you very much!

**Comment by HochCC** [comment]
@PeiliangLi , Hi Peiliang, thanks a lot for your great work and comprehensive paper description. May I ask the mAP performance of the mono branch, if you have evaluated?

**Comment by PeiliangLi** [comment]
hi @XinjieInformatik, yes, but I don't remember the exact number. It underperforms the standard version about 2~3%.

**Comment by HochCC** [comment]
hi @PeiliangLi  thanks! already enough information for me.
