### ISSUE TITLE
low accuracy

### ISSUE THREAD

**Issue by yxy1995123** [HKUST-Aerial-Robotics/Stereo-RCNN#53]
I trained the mono branch and tested without dense alignment.The result is bad.
bbox AP:92.51, 82.42, 67.09
bev  AP:10.17, 6.37, 6.75
3d   AP:6.79, 4.92, 3.72
aos  AP:90.87, 80.31, 64.89
Is it a normal situation?
if not,can you give me some advice?

**Comment by PeiliangLi** [comment]
Yes, it's normal.
In the mono branch, if you don't use the dense alignment, the 3D box is calculated from pure 2d bounding box, which can not guarantee the 3d accuracy.

**Comment by ianw4tm** [comment]
Did you only use one image for everything in the Mono branch?
