### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by Jokoe66** [HKUST-Aerial-Robotics/Stereo-RCNN#6]
when I run the test_net.py for evaluation with ```sh test.sh```,  I got following information :
```
Loaded dataset `kitti_val` for training
Preparing training data...
cache file ./data/kitti/object/kitti_val_gt_roidb.pkl
kitti_val gt roidb loaded from ./data/kitti/object/kitti_val_gt_roidb.pkl
done
3769 roidb entries
load checkpoint models_stereo/stereo_rcnn_18_6477.pth
load model successfully!
Segmentation fault (core dumped)s, solve time 0.41s (Press Esc to exit!) 
```
It seems evaluation works well for a while, but after evalutating about 50 val samples, **Segmentation fault** is reported.
Btw I use cuda8.0 and pytorch 0.3.1, and the training process works just fine.
@PeiliangLi

**Comment by Jokoe66** [comment]
seems it's working well with pytorch 0.3.0

**Comment by PeiliangLi** [comment]
OK, great
