### ISSUE TITLE
Can not reproduce the reported results

### ISSUE THREAD

**Issue by zklgame** [HKUST-Aerial-Robotics/Stereo-RCNN#7]
I have tried several times to reproduce the reported results in the Paper using the public code and config setting, but failed each time. I got results that were 7% worse than the reported number when I used train.txt for training and val.txt for validation. 

Then I decided to run an interesting experiment that I used trainval.txt for training and val.txt for validation, I can reproduce the Paper number! 

Followings are my trained models on train.val and trainlog.txt:

https://pan.baidu.com/s/1zhCt1P3KsVrCyBk8I8kkew
https://pan.baidu.com/s/1P7IXetc1otXtDf0HJQ_7Ug

If any question, please discuss freely.

**Comment by Jokoe66** [comment]
is result evaluated on val set reported in the paper?

**Comment by Jokoe66** [comment]
btw, could you please share your  trained models after each epoch? I'd like to check my training process.
