### ISSUE TITLE
issues about versin based on pytorch 1.0.0 and python 3.6

### ISSUE THREAD

**Issue by Hexuanfang** [HKUST-Aerial-Robotics/Stereo-RCNN#70]
hi! thanks for this awesome work! and i got some problems when i try to use the branch which pytorch=1.0.0, python=3.6. the first one is that i can't download the project by run"git clone git@github.com:HKUST-Aerial-Robotics/Stereo-RCNN.git"  it hints me that"Permission denied (publickey). fatal: Could not read from remote repository." 
and then, i downloaded it by the github bottum, however, more problems appeared, such as: error: invalid command 'develop' , when i run the command "python setup.py build develop",
could you please help me to run this branch correctly? 
thanks in advance

**Comment by Hexuanfang** [comment]
that problem is done, because i didn't add ssh key in the github setting,   thanks for reading anyway!

**Comment by bricksaver** [comment]
Hi. I am experiencing the same problem, but never heard of ssh keys before. How can I find the ssh key to add and how do I add it?
