### ISSUE TITLE
out of memory 

### ISSUE THREAD

**Issue by Yaoxingtian** [HKUST-Aerial-Robotics/Stereo-RCNN#9]
Hi， Peiliang :
when I train the program something happened as below , 
could you kindly tell me what can I do ?
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512378360668/work/torch/lib/THC/generic/THCStorage.cu:58

Another question : where is the light-weight version 
It consumes ~11G GPU memery for training. If your GPU memery is not enough, please try our light-weight version in branch mono.

thanks so much! Hope to get your corresponding asap.

**Comment by PeiliangLi** [comment]
The light-weight version is in the [mono](https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/tree/mono) branch

**Comment by Yaoxingtian** [comment]
I just download the model you provided,  but it is 640M size ,  and the 'out of momery...'   happened again,
are u sure it is light-weight version?

Thanks so much!


发送自 Outlook<http://aka.ms/weboutlook>

________________________________
发件人: Peiliang <notifications@github.com>
发送时间: 2019年4月29日 15:46
收件人: HKUST-Aerial-Robotics/Stereo-RCNN
抄送: Yaoxingtian; Author
主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] out of memory (#9)


The light-weight version is in the mono<https://github.com/HKUST-Aerial-Robotics/Stereo-RCNN/tree/mono> branch

―

**Comment by PeiliangLi** [comment]
First, the model link in the mono branch is different from the one in the master branch. DId you download it correctly?
Second, what is your GPU memory size?

**Comment by Yaoxingtian** [comment]
I know the model is different .
master model is stereo_rcnn_20_6477.pth 846MB or so,  but mono is stereo_rcnn_20_6477.pth 644MB.

my GPU size is six,  it's  ok?

error raised :
RuntimeError: cuda runtime error (2) : out of memory at /opt/conda/conda-bld/pytorch_1512378360668/work/torch/lib/THC/generic/THCStorage.cu:58



发送自 Outlook<http://aka.ms/weboutlook>

________________________________
发件人: Peiliang <notifications@github.com>
发送时间: 2019年4月30日 3:36
收件人: HKUST-Aerial-Robotics/Stereo-RCNN
抄送: Yaoxingtian; Author
主题: Re: [HKUST-Aerial-Robotics/Stereo-RCNN] out of memory (#9)


First, the model link in the mono branch is different from the one in the master branch. DId you download it correctly?
Second, what is your GPU memory size?

―

**Comment by PeiliangLi** [comment]
The mono version consumes about 6.6GB GPU memory for training. Try to reduce the __C.TRAIN.SCALES in the config.
